// Signals
MakeUnsignedCANSignal(data_type_placeholder,0,16,0.1,0) FL_Wheel_Speed_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,16,0.1,-40) FL_Brake_Temperature_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,16,0.1,0) FR_Wheel_Speed_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,16,0.1,-40) FR_Brake_Temperature_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,16,0.1,0) BL_Wheel_Speed_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,16,0.1,-40) BL_Brake_Temperature_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,16,0.1,0) BR_Wheel_Speed_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,16,0.1,-40) BR_Brake_Temperature_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,16,0.1,-40) Motor_Temperature_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,16,0.1,-40) Coolant_Temperature_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,16,0.1,-40) Ambient_Temperature_Signal{};
MakeSignedCANSignal(data_type_placeholder,0,32,1,0) Latitude_Signal{};
MakeSignedCANSignal(data_type_placeholder,32,32,1,0) Longitude_Signal{};
MakeSignedCANSignal(data_type_placeholder,0,16,0.0005,0) Accel_X_Signal{};
MakeSignedCANSignal(data_type_placeholder,16,16,0.0005,0) Accel_Y_Signal{};
MakeSignedCANSignal(data_type_placeholder,32,16,0.0005,0) Accel_Z_Signal{};
MakeSignedCANSignal(data_type_placeholder,0,16,0.0005,0) Gyro_X_Signal{};
MakeSignedCANSignal(data_type_placeholder,16,16,0.0005,0) Gyro_Y_Signal{};
MakeSignedCANSignal(data_type_placeholder,32,16,0.0005,0) Gyro_Z_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,32,1,0) RTC_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_0_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_1_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_2_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_3_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_4_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_5_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_6_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_0_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_7_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_8_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_9_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_10_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_11_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_12_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_13_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_1_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_14_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_15_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_16_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_17_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_18_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_19_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_20_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_2_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_21_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_22_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_23_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_24_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_25_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_26_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_27_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_3_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_28_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_29_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_30_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_31_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_32_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_33_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_34_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_4_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_35_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_36_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_37_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_38_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_39_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_40_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_41_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_5_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_42_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_43_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_44_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_45_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_46_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_47_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_48_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_6_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_49_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_50_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_51_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_52_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_53_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_54_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_55_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_7_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_56_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_57_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_58_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_59_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_60_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_61_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_62_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_8_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_63_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_64_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_65_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_66_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_67_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_68_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_69_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_9_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_70_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_71_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_72_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_73_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_74_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_75_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_76_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_110_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_77_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_78_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_79_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_80_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_81_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_82_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_83_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_211_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_84_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_85_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_86_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_87_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_88_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_89_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_90_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_212_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_91_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_92_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_93_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_94_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_95_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_96_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_97_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_213_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_98_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_99_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_100_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_101_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_102_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_103_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_104_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_214_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_105_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_106_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_107_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_108_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_109_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_110_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_111_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_115_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_112_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_113_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_114_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_115_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_116_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_117_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_118_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_216_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_119_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_120_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_121_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_122_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_123_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_124_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_125_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_217_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_126_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_127_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_128_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_129_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_130_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_131_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_132_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_218_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.012,2) Cell_V_133_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.012,2) Cell_V_134_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.012,2) Cell_V_135_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Cell_V_136_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Cell_V_137_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.012,2) Cell_V_138_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,0.012,2) Cell_V_139_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,56,8,0.004,0) Cell_OCV_Offset_219_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,-40) Cell_T_0_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,-40) Cell_T_1_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,-40) Cell_T_2_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,1,-40) Cell_T_3_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,1,-40) Cell_T_4_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,1,-40) Cell_T_5_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,1,-40) Cell_T_6_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,-40) Cell_T_7_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,-40) Cell_T_8_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,-40) Cell_T_9_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,1,-40) Cell_T_10_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,1,-40) Cell_T_11_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,1,-40) Cell_T_12_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,1,-40) Cell_T_13_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,-40) Cell_T_14_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,-40) Cell_T_15_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,-40) Cell_T_16_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,1,-40) Cell_T_17_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,1,-40) Cell_T_18_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,1,-40) Cell_T_19_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,1,-40) Cell_T_20_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,-40) Cell_T_21_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,-40) Cell_T_22_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,-40) Cell_T_23_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,1,-40) Cell_T_24_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,1,-40) Cell_T_25_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,1,-40) Cell_T_26_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,1,-40) Cell_T_27_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,-40) Cell_T_28_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,-40) Cell_T_29_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,-40) Cell_T_30_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,1,-40) Cell_T_31_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,1,-40) Cell_T_32_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,1,-40) Cell_T_33_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,1,-40) Cell_T_34_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,-40) Cell_T_35_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,-40) Cell_T_36_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,-40) Cell_T_37_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,1,-40) Cell_T_38_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,1,-40) Cell_T_39_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,1,-40) Cell_T_40_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,1,-40) Cell_T_41_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,-40) Cell_T_42_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,-40) Cell_T_43_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,-40) Cell_T_44_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,1,-40) Cell_T_45_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,1,-40) Cell_T_46_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,1,-40) Cell_T_47_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,1,-40) Cell_T_48_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,-40) Cell_T_49_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,-40) Cell_T_50_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,-40) Cell_T_51_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,1,-40) Cell_T_52_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,1,-40) Cell_T_53_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,1,-40) Cell_T_54_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,1,-40) Cell_T_55_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,-40) Cell_T_56_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,-40) Cell_T_57_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,-40) Cell_T_58_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,1,-40) Cell_T_59_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,1,-40) Cell_T_60_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,1,-40) Cell_T_61_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,1,-40) Cell_T_62_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,-40) Cell_T_63_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,-40) Cell_T_64_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,-40) Cell_T_65_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,1,-40) Cell_T_66_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,1,-40) Cell_T_67_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,1,-40) Cell_T_68_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,1,-40) Cell_T_69_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,-40) Cell_T_70_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,-40) Cell_T_71_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,-40) Cell_T_72_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,1,-40) Cell_T_73_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,1,-40) Cell_T_74_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,1,-40) Cell_T_75_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,1,-40) Cell_T_76_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,-40) Cell_T_77_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,-40) Cell_T_78_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,-40) Cell_T_79_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,1,-40) Cell_T_80_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,1,-40) Cell_T_81_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,1,-40) Cell_T_82_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,1,-40) Cell_T_83_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,-40) Cell_T_84_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,-40) Cell_T_85_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,-40) Cell_T_86_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,1,-40) Cell_T_87_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,1,-40) Cell_T_88_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,1,-40) Cell_T_89_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,1,-40) Cell_T_90_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,-40) Cell_T_91_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,-40) Cell_T_92_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,-40) Cell_T_93_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,1,-40) Cell_T_94_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,1,-40) Cell_T_95_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,1,-40) Cell_T_96_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,1,-40) Cell_T_97_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,-40) Cell_T_98_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,-40) Cell_T_99_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,-40) Cell_T_100_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,1,-40) Cell_T_101_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,1,-40) Cell_T_102_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,1,-40) Cell_T_103_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,1,-40) Cell_T_104_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,-40) Cell_T_105_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,-40) Cell_T_106_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,-40) Cell_T_107_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,1,-40) Cell_T_108_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,1,-40) Cell_T_109_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,1,-40) Cell_T_110_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,48,8,1,-40) Cell_T_111_Signal{};
MakeSignedCANSignal(data_type_placeholder,0,8,1,0) Accel_Percentage_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,0) Brake_Percentage_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,0) Torque_Limit_Percentage_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,16,1,0) Front_Brake_Pressure_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,16,1,0) Back_Brake_Pressure_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,12,0.1,0) Max_Discharge_Current_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,12,12,0.1,0) Max_Regen_Current_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,16,0.01,0) Battery_Voltage_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,1,-40) Battery_Temperature_Signal{};
MakeSignedCANSignal(data_type_placeholder,48,16,0.01,0) Battery_Current_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,1,1,0) Fault_Summary_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,1,1,1,0) Undervoltage_Fault_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,2,1,1,0) Overvoltage_Fault_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,3,1,1,0) Undertemperature_Fault_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,4,1,1,0) Overtemperature_Fault_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,5,1,1,0) Overcurrent_Fault_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,6,1,1,0) External_Kill_Fault_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,7,1,1,0) Open_Wire_Fault_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,0) BMS_State_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,1,-40) Max_Cell_Temp_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,1,-40) Min_Cell_Temp_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.012,2) Max_Cell_Voltage_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.012,2) Min_Cell_Voltage_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.5,0) BMS_SOC_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,16,0.01,0) Coolant_Flow_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,0) BMS_Command_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,0) Tractive_System_Status_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.02,0) V5_Rail_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.02,0) V12_Rail_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.02,0) Vbat_Rail_Signal{};
MakeSignedCANSignal(data_type_placeholder,24,16,0.002,0) Vbat_Input_Current_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,40,8,0.05,10) Vbat_Input_Voltage_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,0.1,0) Air_Cooling_Fan_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,8,8,0.1,0) Liquid_Cooling_Fan_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,16,8,0.1,0) Liquid_Cooling_Pump_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,24,8,0.02,0) High_Side_Driver_1_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,32,8,0.02,0) High_Side_Driver_2_Signal{};
MakeUnsignedCANSignal(data_type_placeholder,0,8,1,0) IMD_State_Signal{};

// RX Messages
CANRXMessage<2> FL_Wheel_RX_Message{can_bus, 0x400, FL_Wheel_Speed_Signal, FL_Brake_Temperature_Signal};
CANRXMessage<2> FR_Wheel_RX_Message{can_bus, 0x401, FR_Wheel_Speed_Signal, FR_Brake_Temperature_Signal};
CANRXMessage<2> BL_Wheel_RX_Message{can_bus, 0x402, BL_Wheel_Speed_Signal, BL_Brake_Temperature_Signal};
CANRXMessage<2> BR_Wheel_RX_Message{can_bus, 0x403, BR_Wheel_Speed_Signal, BR_Brake_Temperature_Signal};
CANRXMessage<3> Ptrain_Temps_RX_Message{can_bus, 0x420, Motor_Temperature_Signal, Coolant_Temperature_Signal, Ambient_Temperature_Signal};
CANRXMessage<2> GPS_RX_Message{can_bus, 0x430, Latitude_Signal, Longitude_Signal};
CANRXMessage<3> Accelerometer_RX_Message{can_bus, 0x431, Accel_X_Signal, Accel_Y_Signal, Accel_Z_Signal};
CANRXMessage<3> Gyroscope_RX_Message{can_bus, 0x432, Gyro_X_Signal, Gyro_Y_Signal, Gyro_Z_Signal};
CANRXMessage<1> RTC_RX_Message{can_bus, 0x440, RTC_Signal};
CANRXMessage<8> BMS_Voltages_0_RX_Message{can_bus, 0x200, Cell_V_0_Signal, Cell_V_1_Signal, Cell_V_2_Signal, Cell_V_3_Signal, Cell_V_4_Signal, Cell_V_5_Signal, Cell_V_6_Signal, Cell_OCV_Offset_0_Signal};
CANRXMessage<8> BMS_Voltages_1_RX_Message{can_bus, 0x201, Cell_V_7_Signal, Cell_V_8_Signal, Cell_V_9_Signal, Cell_V_10_Signal, Cell_V_11_Signal, Cell_V_12_Signal, Cell_V_13_Signal, Cell_OCV_Offset_1_Signal};
CANRXMessage<8> BMS_Voltages_2_RX_Message{can_bus, 0x202, Cell_V_14_Signal, Cell_V_15_Signal, Cell_V_16_Signal, Cell_V_17_Signal, Cell_V_18_Signal, Cell_V_19_Signal, Cell_V_20_Signal, Cell_OCV_Offset_2_Signal};
CANRXMessage<8> BMS_Voltages_3_RX_Message{can_bus, 0x203, Cell_V_21_Signal, Cell_V_22_Signal, Cell_V_23_Signal, Cell_V_24_Signal, Cell_V_25_Signal, Cell_V_26_Signal, Cell_V_27_Signal, Cell_OCV_Offset_3_Signal};
CANRXMessage<8> BMS_Voltages_4_RX_Message{can_bus, 0x204, Cell_V_28_Signal, Cell_V_29_Signal, Cell_V_30_Signal, Cell_V_31_Signal, Cell_V_32_Signal, Cell_V_33_Signal, Cell_V_34_Signal, Cell_OCV_Offset_4_Signal};
CANRXMessage<8> BMS_Voltages_5_RX_Message{can_bus, 0x205, Cell_V_35_Signal, Cell_V_36_Signal, Cell_V_37_Signal, Cell_V_38_Signal, Cell_V_39_Signal, Cell_V_40_Signal, Cell_V_41_Signal, Cell_OCV_Offset_5_Signal};
CANRXMessage<8> BMS_Voltages_6_RX_Message{can_bus, 0x206, Cell_V_42_Signal, Cell_V_43_Signal, Cell_V_44_Signal, Cell_V_45_Signal, Cell_V_46_Signal, Cell_V_47_Signal, Cell_V_48_Signal, Cell_OCV_Offset_6_Signal};
CANRXMessage<8> BMS_Voltages_7_RX_Message{can_bus, 0x207, Cell_V_49_Signal, Cell_V_50_Signal, Cell_V_51_Signal, Cell_V_52_Signal, Cell_V_53_Signal, Cell_V_54_Signal, Cell_V_55_Signal, Cell_OCV_Offset_7_Signal};
CANRXMessage<8> BMS_Voltages_8_RX_Message{can_bus, 0x208, Cell_V_56_Signal, Cell_V_57_Signal, Cell_V_58_Signal, Cell_V_59_Signal, Cell_V_60_Signal, Cell_V_61_Signal, Cell_V_62_Signal, Cell_OCV_Offset_8_Signal};
CANRXMessage<8> BMS_Voltages_9_RX_Message{can_bus, 0x209, Cell_V_63_Signal, Cell_V_64_Signal, Cell_V_65_Signal, Cell_V_66_Signal, Cell_V_67_Signal, Cell_V_68_Signal, Cell_V_69_Signal, Cell_OCV_Offset_9_Signal};
CANRXMessage<8> BMS_Voltages_10_RX_Message{can_bus, 0x20a, Cell_V_70_Signal, Cell_V_71_Signal, Cell_V_72_Signal, Cell_V_73_Signal, Cell_V_74_Signal, Cell_V_75_Signal, Cell_V_76_Signal, Cell_OCV_Offset_110_Signal};
CANRXMessage<8> BMS_Voltages_11_RX_Message{can_bus, 0x20b, Cell_V_77_Signal, Cell_V_78_Signal, Cell_V_79_Signal, Cell_V_80_Signal, Cell_V_81_Signal, Cell_V_82_Signal, Cell_V_83_Signal, Cell_OCV_Offset_211_Signal};
CANRXMessage<8> BMS_Voltages_12_RX_Message{can_bus, 0x20c, Cell_V_84_Signal, Cell_V_85_Signal, Cell_V_86_Signal, Cell_V_87_Signal, Cell_V_88_Signal, Cell_V_89_Signal, Cell_V_90_Signal, Cell_OCV_Offset_212_Signal};
CANRXMessage<8> BMS_Voltages_13_RX_Message{can_bus, 0x20d, Cell_V_91_Signal, Cell_V_92_Signal, Cell_V_93_Signal, Cell_V_94_Signal, Cell_V_95_Signal, Cell_V_96_Signal, Cell_V_97_Signal, Cell_OCV_Offset_213_Signal};
CANRXMessage<8> BMS_Voltages_14_RX_Message{can_bus, 0x20e, Cell_V_98_Signal, Cell_V_99_Signal, Cell_V_100_Signal, Cell_V_101_Signal, Cell_V_102_Signal, Cell_V_103_Signal, Cell_V_104_Signal, Cell_OCV_Offset_214_Signal};
CANRXMessage<8> BMS_Voltages_15_RX_Message{can_bus, 0x20f, Cell_V_105_Signal, Cell_V_106_Signal, Cell_V_107_Signal, Cell_V_108_Signal, Cell_V_109_Signal, Cell_V_110_Signal, Cell_V_111_Signal, Cell_OCV_Offset_115_Signal};
CANRXMessage<8> BMS_Voltages_16_RX_Message{can_bus, 0x210, Cell_V_112_Signal, Cell_V_113_Signal, Cell_V_114_Signal, Cell_V_115_Signal, Cell_V_116_Signal, Cell_V_117_Signal, Cell_V_118_Signal, Cell_OCV_Offset_216_Signal};
CANRXMessage<8> BMS_Voltages_17_RX_Message{can_bus, 0x211, Cell_V_119_Signal, Cell_V_120_Signal, Cell_V_121_Signal, Cell_V_122_Signal, Cell_V_123_Signal, Cell_V_124_Signal, Cell_V_125_Signal, Cell_OCV_Offset_217_Signal};
CANRXMessage<8> BMS_Voltages_18_RX_Message{can_bus, 0x212, Cell_V_126_Signal, Cell_V_127_Signal, Cell_V_128_Signal, Cell_V_129_Signal, Cell_V_130_Signal, Cell_V_131_Signal, Cell_V_132_Signal, Cell_OCV_Offset_218_Signal};
CANRXMessage<8> BMS_Voltages_19_RX_Message{can_bus, 0x213, Cell_V_133_Signal, Cell_V_134_Signal, Cell_V_135_Signal, Cell_V_136_Signal, Cell_V_137_Signal, Cell_V_138_Signal, Cell_V_139_Signal, Cell_OCV_Offset_219_Signal};
CANRXMessage<7> BMS_Temperatures_0_RX_Message{can_bus, 0x220, Cell_T_0_Signal, Cell_T_1_Signal, Cell_T_2_Signal, Cell_T_3_Signal, Cell_T_4_Signal, Cell_T_5_Signal, Cell_T_6_Signal};
CANRXMessage<7> BMS_Temperatures_1_RX_Message{can_bus, 0x221, Cell_T_7_Signal, Cell_T_8_Signal, Cell_T_9_Signal, Cell_T_10_Signal, Cell_T_11_Signal, Cell_T_12_Signal, Cell_T_13_Signal};
CANRXMessage<7> BMS_Temperatures_2_RX_Message{can_bus, 0x222, Cell_T_14_Signal, Cell_T_15_Signal, Cell_T_16_Signal, Cell_T_17_Signal, Cell_T_18_Signal, Cell_T_19_Signal, Cell_T_20_Signal};
CANRXMessage<7> BMS_Temperatures_3_RX_Message{can_bus, 0x223, Cell_T_21_Signal, Cell_T_22_Signal, Cell_T_23_Signal, Cell_T_24_Signal, Cell_T_25_Signal, Cell_T_26_Signal, Cell_T_27_Signal};
CANRXMessage<7> BMS_Temperatures_4_RX_Message{can_bus, 0x224, Cell_T_28_Signal, Cell_T_29_Signal, Cell_T_30_Signal, Cell_T_31_Signal, Cell_T_32_Signal, Cell_T_33_Signal, Cell_T_34_Signal};
CANRXMessage<7> BMS_Temperatures_5_RX_Message{can_bus, 0x225, Cell_T_35_Signal, Cell_T_36_Signal, Cell_T_37_Signal, Cell_T_38_Signal, Cell_T_39_Signal, Cell_T_40_Signal, Cell_T_41_Signal};
CANRXMessage<7> BMS_Temperatures_6_RX_Message{can_bus, 0x226, Cell_T_42_Signal, Cell_T_43_Signal, Cell_T_44_Signal, Cell_T_45_Signal, Cell_T_46_Signal, Cell_T_47_Signal, Cell_T_48_Signal};
CANRXMessage<7> BMS_Temperatures_7_RX_Message{can_bus, 0x227, Cell_T_49_Signal, Cell_T_50_Signal, Cell_T_51_Signal, Cell_T_52_Signal, Cell_T_53_Signal, Cell_T_54_Signal, Cell_T_55_Signal};
CANRXMessage<7> BMS_Temperatures_8_RX_Message{can_bus, 0x228, Cell_T_56_Signal, Cell_T_57_Signal, Cell_T_58_Signal, Cell_T_59_Signal, Cell_T_60_Signal, Cell_T_61_Signal, Cell_T_62_Signal};
CANRXMessage<7> BMS_Temperatures_9_RX_Message{can_bus, 0x229, Cell_T_63_Signal, Cell_T_64_Signal, Cell_T_65_Signal, Cell_T_66_Signal, Cell_T_67_Signal, Cell_T_68_Signal, Cell_T_69_Signal};
CANRXMessage<7> BMS_Temperatures_10_RX_Message{can_bus, 0x22a, Cell_T_70_Signal, Cell_T_71_Signal, Cell_T_72_Signal, Cell_T_73_Signal, Cell_T_74_Signal, Cell_T_75_Signal, Cell_T_76_Signal};
CANRXMessage<7> BMS_Temperatures_11_RX_Message{can_bus, 0x22b, Cell_T_77_Signal, Cell_T_78_Signal, Cell_T_79_Signal, Cell_T_80_Signal, Cell_T_81_Signal, Cell_T_82_Signal, Cell_T_83_Signal};
CANRXMessage<7> BMS_Temperatures_12_RX_Message{can_bus, 0x22c, Cell_T_84_Signal, Cell_T_85_Signal, Cell_T_86_Signal, Cell_T_87_Signal, Cell_T_88_Signal, Cell_T_89_Signal, Cell_T_90_Signal};
CANRXMessage<7> BMS_Temperatures_13_RX_Message{can_bus, 0x22d, Cell_T_91_Signal, Cell_T_92_Signal, Cell_T_93_Signal, Cell_T_94_Signal, Cell_T_95_Signal, Cell_T_96_Signal, Cell_T_97_Signal};
CANRXMessage<7> BMS_Temperatures_14_RX_Message{can_bus, 0x22e, Cell_T_98_Signal, Cell_T_99_Signal, Cell_T_100_Signal, Cell_T_101_Signal, Cell_T_102_Signal, Cell_T_103_Signal, Cell_T_104_Signal};
CANRXMessage<7> BMS_Temperatures_15_RX_Message{can_bus, 0x22f, Cell_T_105_Signal, Cell_T_106_Signal, Cell_T_107_Signal, Cell_T_108_Signal, Cell_T_109_Signal, Cell_T_110_Signal, Cell_T_111_Signal};
CANRXMessage<3> Throttle_Values_RX_Message{can_bus, 0x300, Accel_Percentage_Signal, Brake_Percentage_Signal, Torque_Limit_Percentage_Signal};
CANRXMessage<2> Brake_Pressure_RX_Message{can_bus, 0x410, Front_Brake_Pressure_Signal, Back_Brake_Pressure_Signal};
CANRXMessage<5> BMS_SOE_RX_Message{can_bus, 0x240, Max_Discharge_Current_Signal, Max_Regen_Current_Signal, Battery_Voltage_Signal, Battery_Temperature_Signal, Battery_Current_Signal};
CANRXMessage<8> BMS_Faults_RX_Message{can_bus, 0x250, Fault_Summary_Signal, Undervoltage_Fault_Signal, Overvoltage_Fault_Signal, Undertemperature_Fault_Signal, Overtemperature_Fault_Signal, Overcurrent_Fault_Signal, External_Kill_Fault_Signal, Open_Wire_Fault_Signal};
CANRXMessage<6> BMS_Status_RX_Message{can_bus, 0x241, BMS_State_Signal, Max_Cell_Temp_Signal, Min_Cell_Temp_Signal, Max_Cell_Voltage_Signal, Min_Cell_Voltage_Signal, BMS_SOC_Signal};
CANRXMessage<1> Coolant_RX_Message{can_bus, 0x421, Coolant_Flow_Signal};
CANRXMessage<1> BMS_CMD_RX_Message{can_bus, 0x242, BMS_Command_Signal};
CANRXMessage<1> Throttle_Status_RX_Message{can_bus, 0x301, Tractive_System_Status_Signal};
CANRXMessage<5> PDM_Rails_RX_Message{can_bus, 0x500, V5_Rail_Signal, V12_Rail_Signal, Vbat_Rail_Signal, Vbat_Input_Current_Signal, Vbat_Input_Voltage_Signal};
CANRXMessage<5> PDM_Devices_RX_Message{can_bus, 0x501, Air_Cooling_Fan_Signal, Liquid_Cooling_Fan_Signal, Liquid_Cooling_Pump_Signal, High_Side_Driver_1_Signal, High_Side_Driver_2_Signal};
CANRXMessage<1> IMD_RX_Message{can_bus, 0x600, IMD_State_Signal};

// TX Messages
CANTXMessage<2> FL_Wheel_TX_Message{can_bus, 0x400, 4, freq_placeholder, timer_group, FL_Wheel_Speed_Signal, FL_Brake_Temperature_Signal};
CANTXMessage<2> FR_Wheel_TX_Message{can_bus, 0x401, 4, freq_placeholder, timer_group, FR_Wheel_Speed_Signal, FR_Brake_Temperature_Signal};
CANTXMessage<2> BL_Wheel_TX_Message{can_bus, 0x402, 4, freq_placeholder, timer_group, BL_Wheel_Speed_Signal, BL_Brake_Temperature_Signal};
CANTXMessage<2> BR_Wheel_TX_Message{can_bus, 0x403, 4, freq_placeholder, timer_group, BR_Wheel_Speed_Signal, BR_Brake_Temperature_Signal};
CANTXMessage<3> Ptrain_Temps_TX_Message{can_bus, 0x420, 6, freq_placeholder, timer_group, Motor_Temperature_Signal, Coolant_Temperature_Signal, Ambient_Temperature_Signal};
CANTXMessage<2> GPS_TX_Message{can_bus, 0x430, 8, freq_placeholder, timer_group, Latitude_Signal, Longitude_Signal};
CANTXMessage<3> Accelerometer_TX_Message{can_bus, 0x431, 6, freq_placeholder, timer_group, Accel_X_Signal, Accel_Y_Signal, Accel_Z_Signal};
CANTXMessage<3> Gyroscope_TX_Message{can_bus, 0x432, 6, freq_placeholder, timer_group, Gyro_X_Signal, Gyro_Y_Signal, Gyro_Z_Signal};
CANTXMessage<1> RTC_TX_Message{can_bus, 0x440, 4, freq_placeholder, timer_group, RTC_Signal};
CANTXMessage<8> BMS_Voltages_0_TX_Message{can_bus, 0x200, 8, freq_placeholder, timer_group, Cell_V_0_Signal, Cell_V_1_Signal, Cell_V_2_Signal, Cell_V_3_Signal, Cell_V_4_Signal, Cell_V_5_Signal, Cell_V_6_Signal, Cell_OCV_Offset_0_Signal};
CANTXMessage<8> BMS_Voltages_1_TX_Message{can_bus, 0x201, 8, freq_placeholder, timer_group, Cell_V_7_Signal, Cell_V_8_Signal, Cell_V_9_Signal, Cell_V_10_Signal, Cell_V_11_Signal, Cell_V_12_Signal, Cell_V_13_Signal, Cell_OCV_Offset_1_Signal};
CANTXMessage<8> BMS_Voltages_2_TX_Message{can_bus, 0x202, 8, freq_placeholder, timer_group, Cell_V_14_Signal, Cell_V_15_Signal, Cell_V_16_Signal, Cell_V_17_Signal, Cell_V_18_Signal, Cell_V_19_Signal, Cell_V_20_Signal, Cell_OCV_Offset_2_Signal};
CANTXMessage<8> BMS_Voltages_3_TX_Message{can_bus, 0x203, 8, freq_placeholder, timer_group, Cell_V_21_Signal, Cell_V_22_Signal, Cell_V_23_Signal, Cell_V_24_Signal, Cell_V_25_Signal, Cell_V_26_Signal, Cell_V_27_Signal, Cell_OCV_Offset_3_Signal};
CANTXMessage<8> BMS_Voltages_4_TX_Message{can_bus, 0x204, 8, freq_placeholder, timer_group, Cell_V_28_Signal, Cell_V_29_Signal, Cell_V_30_Signal, Cell_V_31_Signal, Cell_V_32_Signal, Cell_V_33_Signal, Cell_V_34_Signal, Cell_OCV_Offset_4_Signal};
CANTXMessage<8> BMS_Voltages_5_TX_Message{can_bus, 0x205, 8, freq_placeholder, timer_group, Cell_V_35_Signal, Cell_V_36_Signal, Cell_V_37_Signal, Cell_V_38_Signal, Cell_V_39_Signal, Cell_V_40_Signal, Cell_V_41_Signal, Cell_OCV_Offset_5_Signal};
CANTXMessage<8> BMS_Voltages_6_TX_Message{can_bus, 0x206, 8, freq_placeholder, timer_group, Cell_V_42_Signal, Cell_V_43_Signal, Cell_V_44_Signal, Cell_V_45_Signal, Cell_V_46_Signal, Cell_V_47_Signal, Cell_V_48_Signal, Cell_OCV_Offset_6_Signal};
CANTXMessage<8> BMS_Voltages_7_TX_Message{can_bus, 0x207, 8, freq_placeholder, timer_group, Cell_V_49_Signal, Cell_V_50_Signal, Cell_V_51_Signal, Cell_V_52_Signal, Cell_V_53_Signal, Cell_V_54_Signal, Cell_V_55_Signal, Cell_OCV_Offset_7_Signal};
CANTXMessage<8> BMS_Voltages_8_TX_Message{can_bus, 0x208, 8, freq_placeholder, timer_group, Cell_V_56_Signal, Cell_V_57_Signal, Cell_V_58_Signal, Cell_V_59_Signal, Cell_V_60_Signal, Cell_V_61_Signal, Cell_V_62_Signal, Cell_OCV_Offset_8_Signal};
CANTXMessage<8> BMS_Voltages_9_TX_Message{can_bus, 0x209, 8, freq_placeholder, timer_group, Cell_V_63_Signal, Cell_V_64_Signal, Cell_V_65_Signal, Cell_V_66_Signal, Cell_V_67_Signal, Cell_V_68_Signal, Cell_V_69_Signal, Cell_OCV_Offset_9_Signal};
CANTXMessage<8> BMS_Voltages_10_TX_Message{can_bus, 0x20a, 8, freq_placeholder, timer_group, Cell_V_70_Signal, Cell_V_71_Signal, Cell_V_72_Signal, Cell_V_73_Signal, Cell_V_74_Signal, Cell_V_75_Signal, Cell_V_76_Signal, Cell_OCV_Offset_110_Signal};
CANTXMessage<8> BMS_Voltages_11_TX_Message{can_bus, 0x20b, 8, freq_placeholder, timer_group, Cell_V_77_Signal, Cell_V_78_Signal, Cell_V_79_Signal, Cell_V_80_Signal, Cell_V_81_Signal, Cell_V_82_Signal, Cell_V_83_Signal, Cell_OCV_Offset_211_Signal};
CANTXMessage<8> BMS_Voltages_12_TX_Message{can_bus, 0x20c, 8, freq_placeholder, timer_group, Cell_V_84_Signal, Cell_V_85_Signal, Cell_V_86_Signal, Cell_V_87_Signal, Cell_V_88_Signal, Cell_V_89_Signal, Cell_V_90_Signal, Cell_OCV_Offset_212_Signal};
CANTXMessage<8> BMS_Voltages_13_TX_Message{can_bus, 0x20d, 8, freq_placeholder, timer_group, Cell_V_91_Signal, Cell_V_92_Signal, Cell_V_93_Signal, Cell_V_94_Signal, Cell_V_95_Signal, Cell_V_96_Signal, Cell_V_97_Signal, Cell_OCV_Offset_213_Signal};
CANTXMessage<8> BMS_Voltages_14_TX_Message{can_bus, 0x20e, 8, freq_placeholder, timer_group, Cell_V_98_Signal, Cell_V_99_Signal, Cell_V_100_Signal, Cell_V_101_Signal, Cell_V_102_Signal, Cell_V_103_Signal, Cell_V_104_Signal, Cell_OCV_Offset_214_Signal};
CANTXMessage<8> BMS_Voltages_15_TX_Message{can_bus, 0x20f, 8, freq_placeholder, timer_group, Cell_V_105_Signal, Cell_V_106_Signal, Cell_V_107_Signal, Cell_V_108_Signal, Cell_V_109_Signal, Cell_V_110_Signal, Cell_V_111_Signal, Cell_OCV_Offset_115_Signal};
CANTXMessage<8> BMS_Voltages_16_TX_Message{can_bus, 0x210, 8, freq_placeholder, timer_group, Cell_V_112_Signal, Cell_V_113_Signal, Cell_V_114_Signal, Cell_V_115_Signal, Cell_V_116_Signal, Cell_V_117_Signal, Cell_V_118_Signal, Cell_OCV_Offset_216_Signal};
CANTXMessage<8> BMS_Voltages_17_TX_Message{can_bus, 0x211, 8, freq_placeholder, timer_group, Cell_V_119_Signal, Cell_V_120_Signal, Cell_V_121_Signal, Cell_V_122_Signal, Cell_V_123_Signal, Cell_V_124_Signal, Cell_V_125_Signal, Cell_OCV_Offset_217_Signal};
CANTXMessage<8> BMS_Voltages_18_TX_Message{can_bus, 0x212, 8, freq_placeholder, timer_group, Cell_V_126_Signal, Cell_V_127_Signal, Cell_V_128_Signal, Cell_V_129_Signal, Cell_V_130_Signal, Cell_V_131_Signal, Cell_V_132_Signal, Cell_OCV_Offset_218_Signal};
CANTXMessage<8> BMS_Voltages_19_TX_Message{can_bus, 0x213, 8, freq_placeholder, timer_group, Cell_V_133_Signal, Cell_V_134_Signal, Cell_V_135_Signal, Cell_V_136_Signal, Cell_V_137_Signal, Cell_V_138_Signal, Cell_V_139_Signal, Cell_OCV_Offset_219_Signal};
CANTXMessage<7> BMS_Temperatures_0_TX_Message{can_bus, 0x220, 8, freq_placeholder, timer_group, Cell_T_0_Signal, Cell_T_1_Signal, Cell_T_2_Signal, Cell_T_3_Signal, Cell_T_4_Signal, Cell_T_5_Signal, Cell_T_6_Signal};
CANTXMessage<7> BMS_Temperatures_1_TX_Message{can_bus, 0x221, 8, freq_placeholder, timer_group, Cell_T_7_Signal, Cell_T_8_Signal, Cell_T_9_Signal, Cell_T_10_Signal, Cell_T_11_Signal, Cell_T_12_Signal, Cell_T_13_Signal};
CANTXMessage<7> BMS_Temperatures_2_TX_Message{can_bus, 0x222, 8, freq_placeholder, timer_group, Cell_T_14_Signal, Cell_T_15_Signal, Cell_T_16_Signal, Cell_T_17_Signal, Cell_T_18_Signal, Cell_T_19_Signal, Cell_T_20_Signal};
CANTXMessage<7> BMS_Temperatures_3_TX_Message{can_bus, 0x223, 8, freq_placeholder, timer_group, Cell_T_21_Signal, Cell_T_22_Signal, Cell_T_23_Signal, Cell_T_24_Signal, Cell_T_25_Signal, Cell_T_26_Signal, Cell_T_27_Signal};
CANTXMessage<7> BMS_Temperatures_4_TX_Message{can_bus, 0x224, 8, freq_placeholder, timer_group, Cell_T_28_Signal, Cell_T_29_Signal, Cell_T_30_Signal, Cell_T_31_Signal, Cell_T_32_Signal, Cell_T_33_Signal, Cell_T_34_Signal};
CANTXMessage<7> BMS_Temperatures_5_TX_Message{can_bus, 0x225, 8, freq_placeholder, timer_group, Cell_T_35_Signal, Cell_T_36_Signal, Cell_T_37_Signal, Cell_T_38_Signal, Cell_T_39_Signal, Cell_T_40_Signal, Cell_T_41_Signal};
CANTXMessage<7> BMS_Temperatures_6_TX_Message{can_bus, 0x226, 8, freq_placeholder, timer_group, Cell_T_42_Signal, Cell_T_43_Signal, Cell_T_44_Signal, Cell_T_45_Signal, Cell_T_46_Signal, Cell_T_47_Signal, Cell_T_48_Signal};
CANTXMessage<7> BMS_Temperatures_7_TX_Message{can_bus, 0x227, 8, freq_placeholder, timer_group, Cell_T_49_Signal, Cell_T_50_Signal, Cell_T_51_Signal, Cell_T_52_Signal, Cell_T_53_Signal, Cell_T_54_Signal, Cell_T_55_Signal};
CANTXMessage<7> BMS_Temperatures_8_TX_Message{can_bus, 0x228, 8, freq_placeholder, timer_group, Cell_T_56_Signal, Cell_T_57_Signal, Cell_T_58_Signal, Cell_T_59_Signal, Cell_T_60_Signal, Cell_T_61_Signal, Cell_T_62_Signal};
CANTXMessage<7> BMS_Temperatures_9_TX_Message{can_bus, 0x229, 8, freq_placeholder, timer_group, Cell_T_63_Signal, Cell_T_64_Signal, Cell_T_65_Signal, Cell_T_66_Signal, Cell_T_67_Signal, Cell_T_68_Signal, Cell_T_69_Signal};
CANTXMessage<7> BMS_Temperatures_10_TX_Message{can_bus, 0x22a, 8, freq_placeholder, timer_group, Cell_T_70_Signal, Cell_T_71_Signal, Cell_T_72_Signal, Cell_T_73_Signal, Cell_T_74_Signal, Cell_T_75_Signal, Cell_T_76_Signal};
CANTXMessage<7> BMS_Temperatures_11_TX_Message{can_bus, 0x22b, 8, freq_placeholder, timer_group, Cell_T_77_Signal, Cell_T_78_Signal, Cell_T_79_Signal, Cell_T_80_Signal, Cell_T_81_Signal, Cell_T_82_Signal, Cell_T_83_Signal};
CANTXMessage<7> BMS_Temperatures_12_TX_Message{can_bus, 0x22c, 8, freq_placeholder, timer_group, Cell_T_84_Signal, Cell_T_85_Signal, Cell_T_86_Signal, Cell_T_87_Signal, Cell_T_88_Signal, Cell_T_89_Signal, Cell_T_90_Signal};
CANTXMessage<7> BMS_Temperatures_13_TX_Message{can_bus, 0x22d, 8, freq_placeholder, timer_group, Cell_T_91_Signal, Cell_T_92_Signal, Cell_T_93_Signal, Cell_T_94_Signal, Cell_T_95_Signal, Cell_T_96_Signal, Cell_T_97_Signal};
CANTXMessage<7> BMS_Temperatures_14_TX_Message{can_bus, 0x22e, 8, freq_placeholder, timer_group, Cell_T_98_Signal, Cell_T_99_Signal, Cell_T_100_Signal, Cell_T_101_Signal, Cell_T_102_Signal, Cell_T_103_Signal, Cell_T_104_Signal};
CANTXMessage<7> BMS_Temperatures_15_TX_Message{can_bus, 0x22f, 8, freq_placeholder, timer_group, Cell_T_105_Signal, Cell_T_106_Signal, Cell_T_107_Signal, Cell_T_108_Signal, Cell_T_109_Signal, Cell_T_110_Signal, Cell_T_111_Signal};
CANTXMessage<3> Throttle_Values_TX_Message{can_bus, 0x300, 3, freq_placeholder, timer_group, Accel_Percentage_Signal, Brake_Percentage_Signal, Torque_Limit_Percentage_Signal};
CANTXMessage<2> Brake_Pressure_TX_Message{can_bus, 0x410, 4, freq_placeholder, timer_group, Front_Brake_Pressure_Signal, Back_Brake_Pressure_Signal};
CANTXMessage<5> BMS_SOE_TX_Message{can_bus, 0x240, 8, freq_placeholder, timer_group, Max_Discharge_Current_Signal, Max_Regen_Current_Signal, Battery_Voltage_Signal, Battery_Temperature_Signal, Battery_Current_Signal};
CANTXMessage<8> BMS_Faults_TX_Message{can_bus, 0x250, 8, freq_placeholder, timer_group, Fault_Summary_Signal, Undervoltage_Fault_Signal, Overvoltage_Fault_Signal, Undertemperature_Fault_Signal, Overtemperature_Fault_Signal, Overcurrent_Fault_Signal, External_Kill_Fault_Signal, Open_Wire_Fault_Signal};
CANTXMessage<6> BMS_Status_TX_Message{can_bus, 0x241, 8, freq_placeholder, timer_group, BMS_State_Signal, Max_Cell_Temp_Signal, Min_Cell_Temp_Signal, Max_Cell_Voltage_Signal, Min_Cell_Voltage_Signal, BMS_SOC_Signal};
CANTXMessage<1> Coolant_TX_Message{can_bus, 0x421, 2, freq_placeholder, timer_group, Coolant_Flow_Signal};
CANTXMessage<1> BMS_CMD_TX_Message{can_bus, 0x242, 8, freq_placeholder, timer_group, BMS_Command_Signal};
CANTXMessage<1> Throttle_Status_TX_Message{can_bus, 0x301, 8, freq_placeholder, timer_group, Tractive_System_Status_Signal};
CANTXMessage<5> PDM_Rails_TX_Message{can_bus, 0x500, 6, freq_placeholder, timer_group, V5_Rail_Signal, V12_Rail_Signal, Vbat_Rail_Signal, Vbat_Input_Current_Signal, Vbat_Input_Voltage_Signal};
CANTXMessage<5> PDM_Devices_TX_Message{can_bus, 0x501, 5, freq_placeholder, timer_group, Air_Cooling_Fan_Signal, Liquid_Cooling_Fan_Signal, Liquid_Cooling_Pump_Signal, High_Side_Driver_1_Signal, High_Side_Driver_2_Signal};
CANTXMessage<1> IMD_TX_Message{can_bus, 0x600, 1, freq_placeholder, timer_group, IMD_State_Signal};
